name: compile

on:
  push:
    branches: [core]
    paths: ["**.zig", "**.dt", "src/inspiration", ".github/workflows/*.yml"]

  pull_request:
    branches: [core]
    paths: ["**.zig", "**.dt", "src/inspiration", ".github/workflows/*.yml"]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2.1.0

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests and cross-compile dt
        run: |
          zig env
          zig build -Doptimize=ReleaseSmall
