name: Push flake to FlakeHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  flakehub:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: actions/checkout@v3
      - name: Push to FlakeHub
        uses: determinatesystems/flakehub-push@main
        with:
          visibility: "public"

